# fly.toml app configuration file generated for go-practice-todo-app on 2024-06-21T04:00:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-practice-todo-app'
primary_region = 'nrt'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  dockerfile = "./backend/Dockerfile.prod"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
